# Use postgres/example user/password credentials
version: '3.9'

services:

  pasada:
    image: postgres:16.2-alpine3.18
    container_name: pasada
    hostname: pasada
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: pasada
      POSTGRES_PASSWORD: dasapa
      POSTGRES_DB: dapasa
    ports:
      - "2345:5432"
