# pasada
version: '3.9'

services:

  pasada:

    image: postgres:16.2-alpine3.18
    restart: always

    container_name: pasada
    hostname: pasada


    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb

    env_file:
      - default.env

    volumes:
      - ./db-data:/var/lib/postgresql/data

    ports:
      - "2345:5432"
